<?php

namespace BackendBundle\Repository;

/**
 * CharactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharactRepository extends \Doctrine\ORM\EntityRepository
{
}
