<?php

namespace BackendBundle\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{

	/* Fonction permettant de sortir 3 valeurs aléatoirement */
	public function getRandom($nb){

		$qb=$this->createQueryBuilder('m');
		
		$results=$qb->getQuery()->getResult();
		shuffle($results);

		return [$results[0], $results[1], $results[2]];

	}

}
