<?php

namespace BackendBundle\Repository;

/**
 * SubgenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubgenreRepository extends \Doctrine\ORM\EntityRepository
{
}
