<?php

namespace BackendBundle\Repository;

/**
 * SubtypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubtypeRepository extends \Doctrine\ORM\EntityRepository
{
}
